channels:
- conda-forge
- defaults
dependencies:
- python=3.12
- pandas>=1.3.0
- numpy>=1.21.0
- plotly>=5.0.0
- openpyxl>=3.0.0
- matplotlib>=3.0.0
- seaborn>=0.10.0
- pathlib2>=2.3.0
name: cp数据分析工具_env
